# NumPy : Fundamentals
---

### *In this notebook we have:*
1. [NumPy Introduction](#1.-numpy-introduction)
2. [Importing and Aliasing numpy](#2.-Importing-and-Aliasing-numpy)
3. [Creating a numpy array](#3.-Creating-a-numpy-array)
4. [Using Ndim Attribute](#4.-ndim-attribute)
5. [Indexing and Slicing](#5.-indexing-and-slicing)
6. [Creating Arrays with Zeros and Ones](#6.-using-zeros()-function-of-numpy)
---

## 1. Numpy Introduction
* NumPy is a library for scientific computing in Python.
* Provides multi-dimensional array object.
* Full form : 'Numerical Python'.

* Why NumPy?
    * Fast to process.

* Install numpy using `pip install numpy` in command prompt.

---
## 2. Importing and Aliasing numpy


In [2]:
import numpy as np
print("numpy imported successfully!!")

numpy imported successfully!!


---
## 3. Creating a numpy array
* Simply call the `array(value)` function.
* It returns ndarray object.
* List, tuple etc.. can be passed as the argument to the funtion.

In [4]:
value = [10,20,30,40,50,60]
array = np.array(value) #creating an array from the list

print(array)

print(type(array)) # returns as the ndarray class

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


---
## 4. ndim attribute
* used to know the dimensions of the array.

In [8]:
value = 2
zero_d = np.array(value)
print("Here is the type of the array:",type(zero_d))
print("Dimensions: ",zero_d.ndim)


Here is the type of the array: <class 'numpy.ndarray'>
Dimensions:  0


In [9]:
value = [10,20,30,40,50,60]
one_d = np.array(value) 
print("Array: ", one_d)
print("Dimensions: ", one_d.ndim)

Array:  [10 20 30 40 50 60]
Dimensions:  1


In [13]:
values = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
two_d = np.array(values)
print("Array: \n",two_d)
print("Dimensions: ", two_d.ndim)

Array: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimensions:  2


---
## 5. Indexing and Slicing

In [ ]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix)
print(matrix[0,0]) #accessing array values through index
print(matrix[0,1])
print(matrix[0,2])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30


In [ ]:
details = [10, 20, 30, 40, 50] 
sales = np.array(details) 
print(sales)
print(sales[2:]) #slicing

[10 20 30 40 50]
[30 40 50]


---
## 6. Using zeros() function of NumPy  

In [ ]:
# np.zeros(col)
sales = np.zeros((5)) #creates 5 columns filled with zeros
print(sales)
print(type(sales))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
# np.zeros(row,col)
sales = np.zeros((5,3)) #creates 5 rows and 3 columns filled with zeros
print(sales)
print(type(sales))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


---
## 7. Using ones() function of numpy

In [25]:
sales = np.ones(5)
print(sales)
print(type(sales))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [27]:
sales = np.ones((5,3)) 
print(sales)
print(type(sales))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


---