# Basic Attributes of NumPy

---
### *In this notebook we have:*
* shape
* ndim
* transpose attribute "T"

---
## Import numpy library

In [1]:
import numpy as np

---
## 1. shape attribute
* Returns the shape of the array, ex: number of rows, number of columns
* Should be accessed using ndarray object.

In [4]:
values = [10, 20, 30], [40, 50, 60]
sales = np.array(values) 
print(sales)
print('Shape:',sales.shape)

[[10 20 30]
 [40 50 60]]
Shape: (2, 3)


In [6]:
values = [10, 20, 30, 40, 50] 
sales = np.array(values) 
print(sales)
print("Shape:",sales.ndim)

[10 20 30 40 50]
Shape: 1


---
## 2. ndim attribute
* Already covered, returns the dimensions of the array.

In [7]:
values = [10, 20, 30], [40, 50, 60]
sales = np.array(values) 
print(sales)
print('Dimensions:',sales.ndim)

[[10 20 30]
 [40 50 60]]
Dimensions: 2


---
## 3. T attribute
* Returns the transpose of the array

In [10]:
values = [10, 20, 30], [40, 50, 60]
sales = np.array(values) 
print(sales)
print('Transpose:\n',sales.T)

[[10 20 30]
 [40 50 60]]
Transpose:
 [[10 40]
 [20 50]
 [30 60]]


---