# Methods in NumPy (only Imp)
---

### *In this notebook we have:*
1. [min() method](#1.-min()-method)  
2. [max() method](#2.-max()-method)  
3. [sum() method](#3.-sum()-method)  
4. [reshape() method](#4.-reshape()-method)  
5. [count_nonzero(p) function](#5.-count_nonzero(p)-function)  
6. [sort() method](#6.-sort()-method)  
7. [flatten() method](#7.-flatten()-method)  
8. [diagonal() method](#8.-diagonal()-method)  
9. [trace() method](#9.-trace()-method)  
10. [add(), subtract() functions](#10.-add()-sub()-different-matrices)  
11. [Performing arithmetic operations on different values](#11.-performing-arithmetic-operations-on-array-values)  

---
## 1. min() method
* method requires array object to invoke it.
* `min()` method checks for the minimum value in the array

In [3]:
import numpy as np

In [4]:
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print("Minimum value:" ,sales.min())

[[10 20 30]
 [40 50 60]]
Minimum value: 10


---
## 2. max() method
* method requires array object to invoke it.
* `max()` method checks for the maximum value in the array

In [5]:
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print("Maximum value:" ,sales.max())

[[10 20 30]
 [40 50 60]]
Maximum value: 60


---
## 3. sum() method
* method requires array object to invoke it.
* `sum()` method returns the sum of the values in the array.

In [6]:
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print("Sum of all the values:" ,sales.sum())

[[10 20 30]
 [40 50 60]]
Sum of all the values: 210


---
## 4. reshape() method
* method requires array object to invoke it.
* `reshape()` method is used to change the **shape** of the array.

In [7]:
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print(sales.shape)
print()
print(sales.reshape(3,2))


[[10 20 30]
 [40 50 60]]
(2, 3)

[[10 20]
 [30 40]
 [50 60]]


In [8]:
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print(sales.shape)
print()
print(sales.reshape(1,6))


[[10 20 30]
 [40 50 60]]
(2, 3)

[[10 20 30 40 50 60]]


In [9]:
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print(sales.shape)
print()
print(sales.reshape(6,1))

[[10 20 30]
 [40 50 60]]
(2, 3)

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


---
## 5. count_nonzero(p) function
* `count_nonzero(p)` function is used to get the count of non zero values in the array.
* Takes array object as an argument.

In [10]:
values = [[10, 0, 30], [40, 50, 0]]
sales = np.array(values) 
print(sales)
print("Count:",np.count_nonzero(sales))

[[10  0 30]
 [40 50  0]]
Count: 4


---
## 6. sort() method
* method requires array object to invoke it.
* `sort()` method is used to sort the values in array.

In [11]:
values = [[10, 5, 30], [40, 32, 63]]
sales = np.array(values) 
print(sales)
sales.sort()
print()
print(sales)

[[10  5 30]
 [40 32 63]]

[[ 5 10 30]
 [32 40 63]]


---
## 7. flatten() method
* method requires array object to invoke it.
* `flatten()` method is used to turn the arrays into 1-D array.

In [12]:
values = [[10, 5, 30], [40, 32, 63]]
sales = np.array(values) 
print(sales)
print()
print(sales.flatten())

[[10  5 30]
 [40 32 63]]

[10  5 30 40 32 63]


---
## 8. diagonal() method
* method requires array object to invoke it.
* `diagonal()` method is used to return the diagonal values of a matrix.

In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print()
print(matrix.diagonal())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 5 9]


---
## 9. trace() method
* method requires array object to invoke it.
* `trace()` method is used to return the sum of the diagonal elements.

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print()
print("Sum of diagonal elements:", matrix.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of diagonal elements: 15


---
## 10. Add, Sub different matrices
* using `add()` and `subtract()` functions of numpy.
* direct addition or subraction is also possible.

In [ ]:
#Matrix Addition:
matrix_a = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 2]])
matrix_b = np.array([[1, 3, 1], [1, 3, 1], [1, 3, 8]])
print("Matrix A:")
print(matrix_a)
print()
print("Matrix B:")
print(matrix_b)
print()
print("Matrix A + Matrix B:")
print(np.add(matrix_a, matrix_b))

Matrix A:
[[1 1 1]
 [1 1 1]
 [1 1 2]]

Matrix B:
[[1 3 1]
 [1 3 1]
 [1 3 8]]

Matrix A + Matrix B:
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


In [20]:
matrix_a = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 2]])
matrix_b = np.array([[1, 3, 1], [1, 3, 1], [1, 3, 8]])
print("Matrix Addition:")
print(matrix_a + matrix_b)

Matrix Addition:
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


In [19]:
#Matrix Subtraction:
matrix_a = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 2]])
matrix_b = np.array([[1, 3, 1], [1, 3, 1], [1, 3, 8]])
print("Matrix A:")
print(matrix_a)
print()
print("Matrix B:")
print(matrix_b)
print()
print("Matrix A - Matrix B:")
print(np.subtract(matrix_a, matrix_b))

Matrix A:
[[1 1 1]
 [1 1 1]
 [1 1 2]]

Matrix B:
[[1 3 1]
 [1 3 1]
 [1 3 8]]

Matrix A - Matrix B:
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [21]:
matrix_a = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 2]])
matrix_b = np.array([[1, 3, 1], [1, 3, 1], [1, 3, 8]])
print("Matrix Subtraction:")
print(matrix_a - matrix_b)

Matrix Subtraction:
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


---
## 11. Performing arithmetic operations on array values

In [ ]:
#Adding a particular value to array values
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print()
print(sales + 2)

[[10 20 30]
 [40 50 60]]

[[12 22 32]
 [42 52 62]]


In [ ]:
#Subtracting a particular value to array values
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print()
print(sales - 2)

[[10 20 30]
 [40 50 60]]

[[ 8 18 28]
 [38 48 58]]


In [ ]:
#Multiplying a particular value to array values
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print()
print(sales * 2)

[[10 20 30]
 [40 50 60]]

[[ 20  40  60]
 [ 80 100 120]]


In [ ]:
#Dividing a particular value to array values
values = [[10, 20, 30], [40, 50, 60]]
sales = np.array(values) 
print(sales)
print()
print(sales // 2)

[[10 20 30]
 [40 50 60]]

[[ 5 10 15]
 [20 25 30]]


---